"""
Five endpoints
--------------
GET  /health
     Liveness check. Confirms data loaded correctly.

GET  /hex/{h3_index}
     Full data for one hex: prediction, Walk Score, top SHAP features,
     raw feature values, demographic data, fold assignment.

GET  /predict/{lat}/{lng}
     Resolves a lat/lng coordinate to its H3 hex, then returns same
     response as /hex. This is what the dashboard map click calls.

POST /compare
     Two hex IDs in the request body. Returns both hexes' full data
     plus a diff showing which features differ most between them.

GET  /city/summary
     City-wide aggregate statistics: mean/median/std of predicted
     scores, top global features by SHAP importance, Moran's I,
     demographic correlation table.

Startup
-------
    uvicorn src.api.main:app --reload --port 8000

Interactive docs (auto-generated by FastAPI):
    http://localhost:8000/docs

Usage examples
--------------
    curl http://localhost:8000/health
    curl http://localhost:8000/predict/41.7794/-87.6444
    curl http://localhost:8000/predict/41.8827/-87.6298
    curl -X POST http://localhost:8000/compare \
         -H "Content-Type: application/json" \
         -d '{"hex_a": "892664c1e17ffff", "hex_b": "892664cde8bffff"}'
    curl http://localhost:8000/city/summary
"""

from __future__ import annotations

import pandas as pd
import geopandas as gpd
import numpy as np
import h3

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from typing import Optional
from pydantic import BaseModel
from contextlib import asynccontextmanager
from loguru import logger
from pathlib import Path


@asynccontextmanager
async def lifespan(app: FastAPI):
    global _shap_df, _master_df, _summary, _feature_cols, _shap_cols

    logger.info("Loading data into memory")

    shap_path = Path("data/processed/shap_values.parquet")
    if not shap_path.exists():
        logger.error(f"Shap values not found: {shap_path}")
        raise RuntimeError("shap_values.parquet not found")


    _shap_df = pd.read_parquet(str(shap_path))
    _shap_df = _shap_df.set_index("h3_index")


    _shap_cols = [c for c in _shap_df.columns
                     if c.startswith("shap_") and c != "shap_baseline"]
    _feature_cols = [c.replace('shap_', "") for c in _shap_cols]

    logger.info(f"SHAP data: {len(_shap_df):,} hexes  {len(_shap_cols)} features")

    master_path = Path("data/processed/master_features.parquet")
    if not master_path.exists():
        logger.warning("master_features.parquet not found — demographic data unavailable")
    else:
        master = gpd.read_parquet(str(master_path))
        keep_cols = [
            "h3_index",
            "centroid_lat", "centroid_lng",
            "census_median_income", "census_pct_poverty",
            "census_pct_minority",  "census_pct_black",
            "census_pct_hispanic",  "census_pop_density",
        ]
        keep_cols  = [c for c in keep_cols if c in master.columns]
        _master_df = master[keep_cols].set_index("h3_index")
        logger.info(f"Master features: {len(_master_df):,} hexes")

    _summary = _compute_city_summary()
    logger.info("All data loaded. Server ready.")

    yield

    logger.info("Server shutting down. Releasing resources.")


# ── App initialisation ─────────────────────────────────────────────────────────
app = FastAPI(
    title="Chicago Walkability Engine",
    description="Predict and explain pedestrian walkability for any Chicago neighborhood",
    version="1.0.0",
    lifespan=lifespan
)

# Allow all origins so the Streamlit dashboard can call this API
app.add_middleware(
    CORSMiddleware,
    allow_origins     = ["*"],
    allow_credentials = True,
    allow_methods     = ["*"],
    allow_headers     = ["*"],
)

# Global states
_shap_df:    Optional[pd.DataFrame]  = None
_master_df:  Optional[pd.DataFrame]  = None
_summary:    Optional[dict]          = None
_feature_cols: Optional[list]        = None
_shap_cols:    Optional[list]        = None

class CompareRequest(BaseModel):
    hex_a: str
    hex_b: str

class HexResponse(BaseModel):
    h3_index:        str
    predicted_score: float
    walk_score:      Optional[float]
    residual:        Optional[float]
    fold_name:       Optional[str]
    top_shap:        list[dict]
    demographics:    dict
    centroid_lat:    Optional[float]
    centroid_lng:    Optional[float]

class CompareResponse(BaseModel):
    hex_a:       HexResponse
    hex_b:       HexResponse
    score_diff:  float
    top_diffs:   list[dict]


class CityResponse(BaseModel):
    n_hexes:         int
    mean_score:      float
    median_score:    float
    std_score:       float
    min_score:       float
    max_score:       float
    top_features:    list[dict]
    score_distribution: dict



def _compute_city_summary() -> dict:
    scores = _shap_df['predicted_score'].values

    shap_matrix = _shap_df[_shap_cols].values
    mean_abs = np.abs(shap_matrix).mean(axis=0)
    top10_idx = np.argsort(mean_abs)[-10:][::-1]
    top_features = [
        {
            'feature':  _feature_cols[i],
            'mean_abs_shap':    round(float(mean_abs[i]), 3),
            'mean_shap':    round(float(shap_matrix[:, i].mean()), 3)
        }
        for i in top10_idx
    ]

    hist, bin_edges = np.histogram(scores, bins=10, range=(0, 100))
    distribution = {
        f"{int(bin_edges[i])}-{int(bin_edges[i+1])}": int(hist[i])
        for i in range(len(hist))
    }

    return {
        "n_hexes":           int(len(scores)),
        "mean_score":        round(float(np.mean(scores)), 2),
        "median_score":      round(float(np.median(scores)), 2),
        "std_score":         round(float(np.std(scores)), 2),
        "min_score":         round(float(np.min(scores)), 2),
        "max_score":         round(float(np.max(scores)), 2),
        "top_features":      top_features,
        "score_distribution": distribution,
    }


def _build_hex_response(h3_index: str) -> HexResponse:
    # ── 1. Look up SHAP row ────────────────────────────────────────────────────
    if h3_index not in _shap_df.index:
        raise HTTPException(
            status_code = 404,
            detail      = (
                f"Hex {h3_index} not found in dataset. "
                "This hex may be outside Chicago's dense area, "
                "on Lake Michigan, or not in the labeled set."
            )
        )

    row = _shap_df.loc[h3_index]

    # ── 2. Scalar fields ───────────────────────────────────────────────────────
    predicted_score = float(row["predicted_score"])
    walk_score      = float(row["walk_score"])      if "walk_score"  in row.index else None
    fold_name       = str(row["fold_name"])          if "fold_name"   in row.index else None
    residual        = round(walk_score - predicted_score, 2) if walk_score else None

    # ── 3. Top 10 SHAP features for this specific hex ─────────────────────────
    shap_vals = row[_shap_cols].values.astype(float)
    abs_shap  = np.abs(shap_vals)
    top10_idx = np.argsort(abs_shap)[-10:][::-1]

    top_shap = [
        {
            "feature":       _feature_cols[i],
            "shap_value":    round(float(shap_vals[i]), 3),
            "direction":     "positive" if shap_vals[i] > 0 else "negative",
        }
        for i in top10_idx
    ]

    # ── 4. Demographics ────────────────────────────────────────────────────────
    demographics = {}
    if _master_df is not None and h3_index in _master_df.index:
        demo_row = _master_df.loc[h3_index]
        demo_keys = [
            "census_median_income", "census_pct_poverty",
            "census_pct_minority",  "census_pct_black",
            "census_pct_hispanic",  "census_pop_density",
        ]
        for key in demo_keys:
            if key in demo_row.index:
                val = demo_row[key]
                demographics[key] = None if pd.isna(val) else round(float(val), 4)

    # ── 5. Centroid coordinates ────────────────────────────────────────────────
    centroid_lat = None
    centroid_lng = None
    if _master_df is not None and h3_index in _master_df.index:
        demo_row = _master_df.loc[h3_index]
        if "centroid_lat" in demo_row.index and not pd.isna(demo_row["centroid_lat"]):
            centroid_lat = round(float(demo_row["centroid_lat"]), 6)
            centroid_lng = round(float(demo_row["centroid_lng"]), 6)

    return HexResponse(
        h3_index        = h3_index,
        predicted_score = round(predicted_score, 2),
        walk_score      = round(walk_score, 1) if walk_score else None,
        residual        = residual,
        fold_name       = fold_name,
        top_shap        = top_shap,
        demographics    = demographics,
        centroid_lat    = centroid_lat,
        centroid_lng    = centroid_lng,
    )


# ── Endpoint 1: /health ────────────────────────────────────────────────────────
@app.get('/health')
async def health():
    if _shap_df is None:
        raise HTTPException(status_code=503, detail='Data not loaded')

    return {
        'status':   'ok',
        'n_hexes':  len(_shap_df),
        'n_features':   len(_shap_cols) if _shap_cols else 0,
        'baseline':   round(float(_shap_df["shap_baseline"].iloc[0]), 2),
        'score_range': {
            "min": round(float(_shap_df["predicted_score"].min()), 1),
            "max": round(float(_shap_df["predicted_score"].max()), 1),
        }
    }


# ── Endpoint 2: /hex/{h3_index} ───────────────────────────────────────────────
@app.get('/hex/{h3_index}', response_model=HexResponse)
async def get_hex(h3_index: str):
    try:
        h3.cell_to_latlng(h3_index)
    except Exception:
        raise HTTPException(
            status_code = 400,
            detail      = f"Invalid H3 cell ID: {h3_index}"
        )

    return _build_hex_response(h3_index)


# ── Endpoint 3: /predict/{lat}/{lng} ──────────────────────────────────────────
@app.get('/predict/{lat}/{lng}', response_model=HexResponse)
async def predict_by_location(lat: float, lng: float):
    if not (41.5 <= lat <= 42.2):
        raise HTTPException(
            status_code =400,
            detail      = f'Latitude {lat} is outside Chicago range (41.5-42.2)'
        )
    if not (-88.1 <= lng <= -87.4):
        raise HTTPException(
            status_code = 400,
            detail      = f'Longtitude {lng} is outside Chicago range (-88.1 to -87.4)'
        )

    h3_index = h3.latlng_to_cell(lat, lng, 9)
    return _build_hex_response(h3_index)


# ── Endpoint 4: POST /compare ─────────────────────────────────────────────────
@app.post('/compare', response_model=CompareResponse)
async def compare_hexes(request: CompareRequest):
    hex_a = request.hex_a
    hex_b = request.hex_b
    hex_a_response = _build_hex_response(hex_a)
    hex_b_response = _build_hex_response(hex_b)

    score_diff = round(hex_a_response.predicted_score - hex_b_response.predicted_score, 2)

    if hex_a in _shap_df.index and hex_b in _shap_df.index:
        shap_a = _shap_df.loc[hex_a, _shap_cols].values.astype(float)
        shap_b = _shap_df.loc[hex_b, _shap_cols].values.astype(float)
        diffs  = shap_a - shap_b

        top_diff_idx = np.argsort(np.abs(diffs))[-10:][::-1]
        top_diffs = [
            {
                "feature":    _feature_cols[i],
                "shap_a":     round(float(shap_a[i]), 3),
                "shap_b":     round(float(shap_b[i]), 3),
                "difference": round(float(diffs[i]),  3),
            }
            for i in top_diff_idx
        ]
    else:
        top_diffs = []

    return CompareResponse(
        hex_a      = hex_a_response,
        hex_b      = hex_b_response,
        score_diff = score_diff,
        top_diffs  = top_diffs,
    )


# ── Endpoint 5: GET /city/summary ─────────────────────────────────────────────
@app.get("/city/summary", response_model=CityResponse)
async def city_summary():
    if _summary is None:
        raise HTTPException(status_code=503, detail="Summary not computed")

    return CityResponse(**_summary)


# ── Bonus endpoint: /neighbourhood/{name} ─────────────────────────────────────
NEIGHBOURHOOD_COORDS = {
    "loop":          (41.8827, -87.6298),
    "lincoln-park":  (41.9214, -87.6513),
    "englewood":     (41.7794, -87.6444),
    "hegewisch":     (41.6497, -87.5525),
    "pilsen":        (41.8535, -87.6650),
    "wicker-park":   (41.9083, -87.6783),
    "hyde-park":     (41.7943, -87.5962),
    "rogers-park":   (42.0118, -87.6683),
    "humboldt-park": (41.8990, -87.7228),
    "austin":        (41.8956, -87.7647),
}


@app.get("/neighbourhood/{name}")
async def get_neighbourhood(name: str):
    name_clean = name.lower().strip()

    if name_clean not in NEIGHBOURHOOD_COORDS:
        available = list(NEIGHBOURHOOD_COORDS.keys())
        raise HTTPException(
            status_code = 404,
            detail      = f"Unknown neighbourhood '{name}'. Available: {available}"
        )

    lat, lng     = NEIGHBOURHOOD_COORDS[name_clean]
    h3_index     = h3.latlng_to_cell(lat, lng, 9)
    response     = _build_hex_response(h3_index)

    result = response.dict()
    result["neighbourhood"] = name_clean
    return result
